export type RequestsGridType = {
    "id": string,
    "year": string,
    "docNum": string,
    "docDate": string,
    "flyDateStart": string,
    "flyDateFinish": string,
    "aircraftTypeName": string,
    "flightTargetName": string,
    "stateName": string,
    "duration": string,
    "durationOut": string,
    "roundDigit": string,
    "cost": string,
    "costOut": string,
    "empCustomerName": string,
    "docCode": string,
    "rejectNote": string,
    "note": string,
    "aircraftModelName": string,
    "airlineName": string,
    "docName": string,
}

export type RequestRoutesGridType = {
    workType: string,
    employee: string,
    dateTime: string,
    airportDeparture: string,
    airportArrival: string,
    passengerCount: string,
    cargoWeightMount: string,
    cargoWeightIn: string,
    cargoWeightOut: string,
    routeId: string,
    id: string,
}

export type RequestData = {
    aircraftModelName: string,
    aircraftTypeName: string,
    airlineName: string,
    cost: string,
    costOut: string,
    docCode: string,
    docDate: string,
    docName: string,
    docNum: string,
    duration: string,
    durationOut: string,
    empCustomerName: string,
    empCustomerLastName: string,
    empCustomerSecondName: string,
    flightTargetName: string,
    flyDateFinish: string,
    flyDateStart: string,
    id: string,
    note: string,
    rejectNote: string,
    roundDigit: string,
    stateName: string,
    year: string,
    routes: RequestRoutesGridType[]
}